AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.gateam.spring.serverless::spring-serverless-with-aws
Resources:
  SpringServerlessWithAwsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gateam.spring.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-serverless-with-aws-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringServerlessWithAwsApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringServerlessWithAwsApi
